import './globals.css'
import { Abhaya_Libre } from 'next/font/google'

const inter = Abhaya_Libre({
  subsets: ['sinhala'],
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
